name: Eval script

on:
  pull_request_target:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - name: Download results.zip
      run: wget https://github.com/$GITHUB_ACTOR/GLUECoS/raw/$GITHUB_HEAD_REF/results.zip
    - name: Run Eval
      run: /root/code/eval.sh results.zip